version: '3'

services:
  app:
    image: verifyme_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - api
    volumes: 
      - ./app:/app
  api:
    image: verifyme_api
    build: .
    ports:
      - 8000:8000
    volumes: 
      - .:/app